<?php

namespace MIT\EsigBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * parcelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parcelleRepository extends EntityRepository
{
}
